# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc 'Maple is used to automate the upgrade and maintenance of libraries.'
  lane :pod_repo_push do |options|
    target_version = options[:version]
    raise "The version is missed. Use `fastlane pod_repo_push version:{version_number}`.`" if target_version.nil?

    ensure_git_status_clean
    ensure_git_branch(branch: "master")
    
    version_bump_podspec(path: "Maple.podspec", version_number: target_version)

    pod_lib_lint(allow_warnings: true)

    git_add(path: ".")
    git_commit(message: "bump version to #{target_version}")
    
    push_to_git_remote

    add_git_tag(tag: target_version)
    push_git_tags

    pod_push(path: "Maple.podspec", allow_warnings: true, repo: "trunk")

    if ENV["GITHUB_TOKEN"]
      set_github_release(
        repository_name: "Mabeple/Maple",
        api_token: ENV["GITHUB_TOKEN"],
        name: "Release #{target_version}",
        tag_name: target_version,
        description: (File.read("CHANGELOG.md") rescue "#{target_version}"),
        commitish: "master",
      )
    else
      UI.important("GITHUB_TOKEN not set, skipping GitHub Release creation")
    end
  end
end
