name: CI

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    branches: 
      - master
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run Tests with Coverage
        run: make coverage        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: .build/debug/codecov/default.profdata
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
