name: Maple

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  Darwin:
    name: Darwin
    runs-on: macos-latest
    env:
      PROJECT: Maple.xcodeproj
      DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer
    steps:
    - uses: actions/checkout@v1
    - name: Bundle Install
      run: bundle install
    - name: Brew Upgrade
      run: |
        brew update
        brew outdated xctool || brew upgrade xctool
    - name: Test iOS
      run: |
        xcodebuild clean build test -project $PROJECT -scheme $SCHEME -destination "$DESTINATION" | XCPRETTY_JSON_FILE_OUTPUT="xcodebuild-ios.json" xcpretty -f `xcpretty-json-formatter`
        bash <(curl -s https://codecov.io/bash) -cF ios -J 'Maple'
      env:
          SCHEME: Maple-iOS
          DESTINATION: platform=iOS Simulator,name=iPhone 11
    - name: Test MacOS
      run: |
        xcodebuild clean build test -project $PROJECT -scheme $SCHEME -destination "$DESTINATION" | XCPRETTY_JSON_FILE_OUTPUT="xcodebuild-macos.json" xcpretty -f `xcpretty-json-formatter`
        bash <(curl -s https://codecov.io/bash) -cF macos -J 'Maple'
      env:
          SCHEME: Maple-macOS
          DESTINATION: platform=OS X
      
  Linux:
    runs-on: [ubuntu-16.04] 
    container: swift:5.2.3
    steps:
      - uses: actions/checkout@v1
      - name: Linux
        run: swift test --enable-test-discovery --parallel
